[project]
name = "aireviewer"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["google-genai", "GitPython"]

[project.scripts]
review = "aireviewer.cli:main"

[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__"]
typeCheckingMode = "strict"
